# CREATE MODEL TO HANDLE VALIDATIONS
rails_command("g model GuestUser uniqname:string ")

gsub_file('app/models/guest_user.rb',  'class GuestUser < ApplicationRecord', 'class GuestUser')

insert_into_file 'app/models/guest_user.rb', after: "class GuestUser\n" do
  <<-GUEST_MODEL
  include ActiveModel::Model

  def initialize(session)
    @session = session
  end

  def uniqname
    'Guest'
  end
  GUEST_MODEL
end

## UPDATE APPLICATION Helpers
insert_into_file "app/helpers/application_helper.rb", before: 'end' do
  <<-APPLICATION_HELPER

  def sign_in_url
    @link = request.original_url.split('//')[1]
    @link = "https://#{@link}"
  end

  def sign_out_url
    @link = request.original_url.split('//')[1]
    @link = "https://weblogin.umich.edu/cosign-bin/logout?http://#{@link}"
  end

  def sign_in_sign_out_link
    if @current_user.uniqname == 'Guest'
      link_to 'Sign In', sign_in_url
    else
      link_to 'Sign Out', sign_out_url
    end
  end

  APPLICATION_HELPER
end

rails_command('g scaffold User create destroy uniqname:string')
# ADD ROUTES
insert_into_file 'config/routes.rb', before: 'end' do
  <<-FEEDBACK_ROUTE
  resources 'feedbacks', only: [:create]
  FEEDBACK_ROUTE
end

## UPDATE APPLICATION CONTROLLER
insert_into_file 'app/controllers/application_contoller.rb', after: 'before_action' do
  " :current_user, "
end
insert_into_file 'app/controllers/application_controller.rb', after: "private\n" do
  <<-APPLICATION_HELPER

    def current_user
      remote_user = request.headers.env.fetch('REMOTE_USER') {nil}
      if remote_user
        @current_user = User.find_or_create_by(uniqname: remote_user)
      else
        @current_user = GuestUser.new(session)
      end
    end

  APPLICATION_HELPER

# GENERATE MAILER

rails_command('g mailer Feedback')

insert_into_file 'app/mailers/feedback_mailer.rb', after: 'ApplicationMailer' do

  <<-FEEDBACKS_MAILER

  def send_feedback(feedback)
    @greeting = "This is a greeting"
    @body = 'This message was generated by a default template. To customize your message, look at app/mailers/feedback_mailer.rb'
    mail to: 'dschmura@humbledaisy.com', subject: @greeting, from: feedback.email, bcc: feedback.email
  end

  FEEDBACKS_MAILER
end

# CREATE MODAL FORM
# This is a bootstrap version.
file 'app/views/feedback/_feedback.html.haml'
  append_to_file 'app/views/feedback/_feedback.html.haml' do
    <<-BOODSTRAP_FEEDBACK_MODAL
/ Button trigger modal
%button.btn.btn-primary{"data-target" => "#contact-mailer--modal", "data-toggle" => "modal", :type => "button"}
  Feedback
/ Modal
#contact-mailer--modal.modal.fade.bd-example-modal-md{"aria-hidden" => "true", "aria-labelledby" => "contact-mailer--modalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-md{:role => "document"}
    .modal-content
      .modal-header
        %h4.modal-title Submit Your Feedback
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_with model: @feedback do |f|
          .form-group
            = notice
            = @feedback.errors.full_messages.join(', ')
          .form-group
            = f.label :full_name, 'Full name', :class => "control-label"
            #form_div
              = f.text_field :full_name, placeholder: 'Full Name'
          .form-group
            = f.label :email, 'eMail', :class => "control-label"
            #form_div
              = f.email_field :email, placeholder: 'email@somewhere.com', required: true
          .form-group
            = f.label :topic, 'Topic', :class => "control-label"
            #form_div
              = f.select(:topic, options_for_select([['I have some feedback...','feedback'],['I have a question...', 'question'],['I have a feature request...','feature'],['I’d like to report a bug...','bug'],['Other','other']],1))
          .form-group
            = f.label :comment, 'Comment', :class => "control-label"
            #form_div
              = f.text_area :comment, placeholder: 'Comment', required: true
          .form-group
            #form_div
              = f.submit :submit, :class => "btn btn-success"

    BOODSTRAP_FEEDBACK_MODAL
end

# # SETUP ENVIRONMENTS FOR mailer
# insert_into_file 'config/environments/development.rb', after: 'Rails.application.configure do' do
#   <<-DEVELOPMENT_ENVIRONMENT
#
#   config.action_mailer.delivery_method = :letter_opener
#
#   DEVELOPMENT_ENVIRONMENT
# end

insert_into_file 'config/environments/production.rb', after: 'Rails.application.configure do' do
  <<-PRODUCTION_ENVIRONMENT

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address:              Rails.application.credentials.#{app_name.upcase}_EMAIL_SERVER,
    domain:               Rails.application.credentials.#{app_name.upcase}_EMAIL_DOMAIN,
    user_name:            Rails.application.credentials.#{app_name.upcase}_EMAIL_USERNAME,
    password:             Rails.application.credentials.#{app_name.upcase}_EMAIL_PASSWORD,
    authentication:       :login,
    enable_starttls_auto: 'true',
    port:                 '587'
  }

  PRODUCTION_ENVIRONMENT
end

# ADD PARTIAL TO RENDER ON THE FOOTER
append_to_file 'app/views/layouts/_footer.html.haml', after: '.footer-contact' do
  <<-FEEDBACK_LINK

    = render 'feedback/feedback'
  FEEDBACK_LINK
end

file 'app/views/feedback_mailer/send_feedback.html.haml'
file 'app/views/feedback_mailer/send_feedback.text.haml'

# ADD CREATE_FEEDBACK ACTION TO APPLICATION CONTROLLER
insert_into_file 'app/controllers/application_controller.rb', after: "class ApplicationController < ActionController::Base\n" do
  <<-CONTROLLER_ACTION
  before_action :create_feedback

  private
  def create_feedback
    @feedback = Feedback.new
  end
  CONTROLLER_ACTION

end

insert_into_file 'app/views/pages/contact.html.haml', after: '%p Find me in app/views/pages/contact.html.haml' do
  <<-CONTACT_PAGE_FORM


.container.text-center.contact-us--form
  %h1 Pages#contact
  %p Find me in app/views/pages/contact.html.haml
  %h3.heading-style-1.text-center.text-uppercase.text-weight-normal
    Contact Us
  = form_with model: @feedback, class: 'contact-us-page--form' do |f|

    .form-group
      = notice
      = @feedback.errors.full_messages.join(', ')

    .form-group
      = f.text_field :full_name, placeholder: 'Full Name'

    .form-group
      = f.email_field :email, placeholder: 'email@somewhere.com', required: true

    .form-group
      = f.label :topic, 'Topic', :class => "control-label"
      = f.select(:topic, options_for_select([['I have some feedback...','feedback'],['I have a question...', 'question'],['I have a feature request...','feature'],['I’d like to report a bug...','bug'],['Other','other']],1))

    .form-group
      = f.text_area :comment, placeholder: 'What is on your mind?', required: true

    .form-group
      = f.submit :submit, :class => "btn btn-success"


  CONTACT_PAGE_FORM
end

file "app/webpacker/#{app_name}/stylesheets/_contact_us_page.sass"
append_to_file "app/webpacker/#{app_name}/stylesheets/_contact_us_page.sass" do
  <<-CONTACT_STYLE
.contact-us--form
.contact-us-page--form
  #feedback_full_name
  #feedback_email
  #feedback_topic
  #feedback_comment
  CONTACT_STYLE
end

# ALLOW SCRIPTS TO BE LOADED ON HTTP (LESS SECURE)
  print
  "there's a new initializer called content_security_policy.rb - in there you'll find a line like this:\n
  .script_src :self, :https\n
  \n
  change it to:\n
  \n
  p.script_src :self, :https, :unsafe_inline\n"
